### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mnoskov** [amcms/quad#1]
1. [x] Комментарии [-comment-], [[-, {{-;
2. [x] Экранирование тегов @{{, @[[ и т.д.;
3. [x] Базовые фильтры в составе пакета;

**Comment by mnoskov** [comment]
Фильтры: is, not, gt, gte, lt, lte, empty, contains, in, then, else, append, capitalize, default, date_format, ellipsis, escape, htmlentities, lower, nl2br, prepend, round, striptags, strtotime, trim, upper, ucfirst, ucwords, urlencode, urldecode, wordwrap

**Comment by mnoskov** [comment]
https://github.com/modxcms/revolution/blob/6fc6fa7bda7c1623ab8e85fbc20313d5b578de82/core/model/modx/filters/modoutputfilter.class.php

**Comment by ShCoder-1** [comment]
+number_format к базовым фильтрам, можно будет уже на будущее заложить, чтобы сейчас не отвлекаться
